# Generated by Django 4.2.7 on 2026-01-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="cloudinary_public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Cloudinary public ID for the file",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="cloudinary_resource_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloudinary resource type (image, video, raw)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="cloudinary_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cloudinary secure URL for the file",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["cloudinary_public_id"], name="operations__cloudin_e348bc_idx"
            ),
        ),
    ]
